spring.application.name=expensetrackerapi
spring.datasource.url=jdbc:postgresql://localhost:5432/expensetracker
spring.datasource.username=postgres
spring.datasource.password=supersecure
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
