spring.application.name=expensetrackerapi
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
jwt.secret=${JWT_SECRET}
jwt.expiration=604800000
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN}
