spring.jpa.show-sql=true
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/expensetracker}
spring.datasource.username=${DB_USERNAME:postgres}
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:5173}
