CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(50) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    date TIMESTAMP NOT NULL,
    category VARCHAR(255) NOT NULL,
    transaction_type VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT expenses_category_check
        CHECK (
            category IN (
                'FOOD',
                'UTILITIES',
                'ENTERTAINMENT',
                'TRANSPORT',
                'CLOTHING',
                'BILLS',
                'GIFT',
                'GAS',
                'HOME',
                'CAR',
                'TRAVEL',
                'MISC',
                'OTHER'
            )
        ),

    CONSTRAINT expenses_transaction_type_check
        CHECK (
            transaction_type IN (
                'CREDIT',
                'INCOME',
                'EXPENSE',
                'TRANSFER',
                'INVESTMENT',
                'SALARY',
                'OTHER'
            )
        ),

    CONSTRAINT fk_expenses_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);

CREATE TABLE budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(10, 2) NOT NULL,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_budgets_user
        FOREIGN KEY (user_id)
        REFERENCES users(id),

    CONSTRAINT uk_budgets_user_year_month
        UNIQUE (user_id, year, month)
);